#!/usr/bin/env bash

bspc monitor -d 1 2 3 4 5 6

bspc config border_width 2
bspc config window_gap 7
bspc config focused_border_color "#ff5f00"
bspc config split_ratio          0.5

#bspc rule -a Alacritty desktop='^3'
#bspc rule -a Chromium desktop='^2'

pkill sxhkd
pkill polybar


feh --bg-fill ~/dotfiles/wallpapers/power-line.png &
sxhkd &
~/.config/polybar/launch.sh &
betterlockscreen -u ~/dotfiles/wallpapers/power-line.png &
