----- Normal mode -----
nnmap('<c-w>', 'ZZ')
nnmap('<tab>', '<cmd>BufferNext<cr>')
nnmap('<s-tab>', '<cmd>BufferPrevious<cr>')
nnmap('<space><space>', '<cmd>Files<cr>')
nnmap('Q', '<nop>')
nnmap('<space>sn', ':e ~/dotfiles/snippets/<c-r>=expand(&ft)<cr>.json<cr>')
nnmap('<space>rg', '<cmd>Rg<cr>')
nnmap('<c-s>', '<cmd>w<cr>')

----- Instert mode -----
inmap('[', '[]<left>')
inmap('{', '{}<left>')
inmap('(', '()<left>')
inmap('<down>', 'v:lua.down()', {expr = true})
inmap('<up>', 'v:lua.up()', {expr = true})
inmap(')', 'v:lua.r_pren()', {expr = true})
inmap('}', 'v:lua.r_brace()', {expr = true})
inmap(']', 'v:lua.r_bracket()', {expr = true})
inmap('<bs>', 'v:lua.backspace()', {expr = true})
inmap('<cr>', 'v:lua.enter()', {expr = true})
inmap('<space>', 'v:lua.space()', {expr = true})
inmap('<c-space>', 'compe#complete()', {expr = true})
imap('<tab>', 'v:lua.tab()', {expr = true})
imap('<c-j>', 'v:lua.c_j()', {expr = true})
imap('<c-k>', 'v:lua.c_k()', {expr = true})
