 -- local ls = require("luasnip")
-- local s = ls.snippet
-- local t = ls.text_node
-- local i = ls.insert_node
-- local f = ls.function_node
-- local function copy(args)
	-- return args[1]
-- end

-- ls.add_snippets("lua", {
 --  	s("xx", {
		-- t("//Parameters: "),
		-- f(copy, 2),
		-- t({ "", "function " }),
		-- i(1),
		-- t("("),
		-- i(2, "int foo"),
		-- t({ ") {", "\t" }),
		-- i(0),
		-- t({ "", "}" }),
	-- }),
 -- })

